version: '3'
services:

    bingo:
        image: node:latest
        ports:
            - 8080:8080
        expose:
            - 8080
        tty: true
        command: npm start
        volumes:
            - ./app:/app
        working_dir: /app
        networks:
            - secure
        env_file:
            - .env.local

networks:
    secure:
        driver: bridge
